# -*- coding: utf-8 -*-
"""scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hW0m3z1Td17NNemLxh2sr2zoWhzyKV5n
"""

!pip install google_play_scraper

from google_play_scraper import app
import pandas as pd
import numpy as np

from google_play_scraper import reviews, Sort

result, continuation_token = reviews(
    'com.dts.freefiremax',
    lang='id',
    country='id',
    sort=Sort.NEWEST,   # pakai Sort, bukan sort
    count=2000,
    filter_score_with=None
)

df_busu = pd.DataFrame(np.array(result),columns=['review'])
df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))
df_busu.head()

len(df_busu.index)

df_busu[['userName', 'score', 'at', 'content']].head()

my_df = df_busu[['userName', 'score', 'at', 'content']]

my_df.to_csv("scraperdata_freefirereviews.csv", index = False)

"""https://youtu.be/-QUyD0YFYb0?si=r5gOIRwQH_i7zpcq"""